### ISSUE TITLE
component structure

### ISSUE THREAD

**Issue by ronanyeah** [shahenazmonia/tech-resource#15]
1. move the component structure from center.jsx into index.jsx
2. delete center.jsx
3. index.jsx should be the only file importing the store. use the passing of dispatch actions as props to child components to manage this

ask questions on gitter if you have any problems. see my iLearn file for an example

**Comment by mhmdshorafa** [comment]
done .. why we shouldn't import store more than once .. is it about app performance ??

**Comment by ronanyeah** [comment]
no its to enforce good application structure. the data from the store should come from the top, and flow down through the components.
```
store ->
  ilearn ->
    form
    list
```
instead of
```
store -> ilearn
store -> form
store -> list
```

**Comment by ronanyeah** [comment]
this has not been resolved
https://github.com/shahenazmonia/tech-resource/blob/master/src/frontEnd/myTable.jsx#L5
this component should be receiving the data through props

only import the store in ONE place, index.jsx

**Comment by ronanyeah** [comment]
and link to the commit that makes the changes when you close the issue :+1:
