### ISSUE TITLE
Weird string construction.

### ISSUE THREAD

**Issue by ronanyeah** [shahenazmonia/tech-resource#34]
https://github.com/shahenazmonia/tech-resource/blob/master/src/frontEnd/actions.js#L34

**Comment by shahenazmonia** [comment]
https://github.com/shahenazmonia/tech-resource/blob/master/src/frontEnd/actions.js#L34
https://github.com/shahenazmonia/tech-resource/blob/master/src/frontEnd/actions.js#L45
