### ISSUE TITLE
Never ask the user to do a global install.

### ISSUE THREAD

**Issue by ronanyeah** [shahenazmonia/tech-resource#40]
https://github.com/shahenazmonia/tech-resource/blob/master/README.md

Put nodemon in the dev dependencies and the script will be able to use it.

**Comment by shahenazmonia** [comment]
Nodemon in package.js now, and remove the sentance from README 
:)

**Comment by ronanyeah** [comment]
https://github.com/shahenazmonia/tech-resource/commit/8eadaf1470cfcd0695688a04fc04d879d8e2173f
