### ISSUE TITLE
Editing experience needs to be finished.

### ISSUE THREAD

**Issue by ronanyeah** [shahenazmonia/tech-resource#43]
The experience of editing the rows is pretty bad. I think the simplest solution would be to put a `currentlyEditing` field in the store, that is either an id corresponding to a row, or `null`. Your table component should be able to figure out the rest.
https://github.com/shahenazmonia/tech-resource/blob/b67d15471141504e2f89f4e9827093a1f7c90119/src/frontEnd/store.js#L6

**Comment by ronanyeah** [comment]
So you will need another reducer and more actions.

**Comment by ronanyeah** [comment]
Actually on second thoughts this should be in the state of the table, not the store.

**Comment by mhmdshorafa** [comment]
check it now ... it fixed it using the store

**Comment by mhmdshorafa** [comment]
should i do it using table state ?

**Comment by ronanyeah** [comment]
@mhmdshorafa Yeah I think so.

**Comment by ronanyeah** [comment]
This will do for now though, I'll have a look. :+1:
