### ISSUE TITLE
Edit state is overly complicated.

### ISSUE THREAD

**Issue by ronanyeah** [shahenazmonia/tech-resource#45]
The edit value is an array of objects for some reason? Just have it as a number or `null`. A number means that that id/row is currently being edited, and `null` means nothing is currently being edited. So the initial state for edit is `null`, when you dispatch `UPDATE_TR` the payload will be an id, and when you finish editing/dispatch `FREEZE_TR` the payload will be `null`.
https://github.com/shahenazmonia/tech-resource/blob/master/src/frontEnd/reducers.js#L20

**Comment by ronanyeah** [comment]
`const editReducer = (state = null, action) => {`

`id => store.dispatch({ type: 'UPDATE_TR', payload: id });`

In fact, freeze doesn't need a payload as it always returns null.
`store.dispatch({ type: 'FREEZE_TR' });`

**Comment by mhmdshorafa** [comment]
take a look now if it's ok

**Comment by ronanyeah** [comment]
When you fix an issue please put a link to the commit that fixed it.

**Comment by mhmdshorafa** [comment]
https://github.com/shahenazmonia/tech-resource/commit/e524f768dee2a86c955dbd47f199843ef19a974f

**Comment by ronanyeah** [comment]
Starting to look good!

This is a mess:
https://github.com/shahenazmonia/tech-resource/blob/e524f768dee2a86c955dbd47f199843ef19a974f/src/frontEnd/components/myTable.jsx#
```
(this.props.trStatus===null)?false
:(this.props.trStatus==elem.id)?true:false
```
can be replaced by:
```
this.props.trStatus === elem.id
```

**Comment by mhmdshorafa** [comment]
https://github.com/shahenazmonia/tech-resource/pull/56/commits/a274377d485161fd9aa0445449cdd5a83c02b2a1
(y)
