### ISSUE TITLE
Change eslint script.

### ISSUE THREAD

**Issue by ronanyeah** [shahenazmonia/tech-resource#46]

**Comment by mhmdshorafa** [comment]
i run command "npm run lint" on my computer and it's ok .. how should i know if there is a problem ?

**Comment by ronanyeah** [comment]
It was a console.log but it got removed.
You should change your eslint script to `eslint --ext .jsx --ext .js .` so that is checks both file types as well. :+1:

**Comment by ronanyeah** [comment]
(link to the commit when it's done)

**Comment by mhmdshorafa** [comment]
https://github.com/shahenazmonia/tech-resource/pull/53/commits/19c0de03621f3f365ed4a7a7117fd61104f0ef9e

**Comment by ronanyeah** [comment]
This commit changed two files. Only one of them is relevant to this commit. I'll let it pass now but be more careful in future.
Use https://git-cola.github.io/ if you need help managing your commits.
