### ISSUE TITLE
Unnecessary code in tests.

### ISSUE THREAD

**Issue by ronanyeah** [shahenazmonia/tech-resource#50]
Do these lines do anything?
https://github.com/shahenazmonia/tech-resource/blob/master/src/frontEnd/reducer.test.js#L26
https://github.com/shahenazmonia/tech-resource/blob/master/src/frontEnd/reducer.test.js#L35
https://github.com/shahenazmonia/tech-resource/blob/master/src/frontEnd/reducer.test.js#L43

**Comment by mhmdshorafa** [comment]
https://github.com/shahenazmonia/tech-resource/pull/55/commits/a27079e6fcedec2faf3055a7c04fd5ac5989aa5d

sorry i didn't see the two files message untill now ... this commit for the weired test and and for unnecessary code issues ..


i wante to enject reducer with FETCH_POST_SUCCESS action before doing the FETCH_POST_FAILED  test 
https://github.com/shahenazmonia/tech-resource/blob/master/src/frontEnd/reducer.test.js#L25
i deleted the extra line in this test
https://github.com/shahenazmonia/tech-resource/blob/master/src/frontEnd/reducer.test.js#L34

i want to enject reducer with UPDATE_TR action before doing the test 
https://github.com/shahenazmonia/tech-resource/blob/master/src/frontEnd/reducer.test.js#L41

i will fix one issue each time in the next time

**Comment by ronanyeah** [comment]
I don't know what you mean by inject. You are just calling a function twice. The second time is tested, the first time isn't.

**Comment by mhmdshorafa** [comment]
I just want to test failing action while the state has values from the success action ..it seems that it is  not neccessary ..i'll delete it

**Comment by ronanyeah** [comment]
Reducers are pure functions. They accept arguments, and return results. There is no 'setup' involved.

**Comment by ronanyeah** [comment]
It is very important to understand this. If you want a different state for your action to change, then pass in a different state.

**Comment by ronanyeah** [comment]
Freeze test:
`expect(editReducer(1, {'FREEZE_TR'})).toEqual(null);`
Start edit test:
`expect(editReducer(null, {'UPDATE_TR', payload: 1})).toEqual(1);`

**Comment by mhmdshorafa** [comment]
https://github.com/shahenazmonia/tech-resource/pull/57/commits/fb96b1809c07c975c958ee92a7b5c8ba70d7646d
