### ISSUE TITLE
Weird test.

### ISSUE THREAD

**Issue by ronanyeah** [shahenazmonia/tech-resource#51]
https://github.com/shahenazmonia/tech-resource/blob/master/src/frontEnd/reducer.test.js#L27

A reducer accepts two parameters, 1. that part of the store, 2. an action.

Here you are passing in an array as an action.
`expect(resourcesReducer([], [])).toEqual([]);`

**Comment by mhmdshorafa** [comment]
https://github.com/shahenazmonia/tech-resource/blob/master/src/frontEnd/reducer.test.js#L26

you can check this test now
